name: 'meps'
version: '1.0.0'
config-version: 2

profile: 'meps'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  meps:
    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table